// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package postgres

import (
	"context"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/jackc/pgconn"
	"github.com/jackc/pgx/v5"
)

type DBTX interface {
	Exec(context.Context, string, ...any) (pgconn.CommandTag, error)
	Query(context.Context, string, ...any) (pgx.Rows, error)
	QueryRow(context.Context, string, ...any) pgx.Row
}

func New(db *pgxpool.Pool) *Queries {
	return &Queries{db}
}

type Queries struct {
	db *pgxpool.Pool
}
