// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package postgres

import (
	"database/sql"
	"time"
)

type TogoTask struct {
	ID          int64
	Name        string
	Description string
	CreatedOn   time.Time
	CompletedOn sql.NullTime
	DueDate     sql.NullTime
}
