openapi: 3.0.0
info:
  title: ToGo - a to do application written in Go
  description: A simple and largely pointless application that demonstrates building things in Go.
  version: 0.1.0

servers:
  - URL: /api

paths:
  /project:
    post:
      summary: Create or update a project's metadata.
      description: Creates or updates the metadata of a project. This _does not_ save any tasks associated with the project. To avoid n+1 storms, just save changes individually.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '201':
          description: 'Accepted'
          content:
            text/plain:
              schema:
                type: string
                format: text
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    get:
      summary: Retrieve a project by name.
      description: Look up a project by name and return a Project object. Returns a 404 if the 
        project cannot be found in the backing store.
      parameters:
        - name: projectName
          in: header
          schema:
            type: string
          description: The name of the project to retrieve.
          required: true
          allowEmptyValue: false
      responses:
        '200':
          description: 'Found'
          content:
            requestBody:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: 'Not found'
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'

components:
  schemas:
    Project:
      type: object
      properties:
        name:
          type: string
          description: Project name. Must be unique across all projects.
        description:
          type: string
          description: Project description
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          format: text
          description: A URI reference [RFC3986] that identifies the problem type.
        title:
          type: string
          format: text
          description: A short, human-readable summary of the problem type.
        status:
          type: integer
          description: The HTTP status code ([RFC7231], Section 6) generated by the origin server 
            for this occurrence of the problem.
        detail:
          type: string
          format: text
          description: A human-readable explanation specific to this occurrence of the problem.
        instance:
          type: string
          format: text
          description: A URI reference that identifies the specific occurrence of the problem.
      additionalProperties: true

